# Generated by Django 4.2.6 on 2023-10-29 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0002_alter_file_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(upload_to='C:\\Users\\bormo\\Documents\\python\\testdup\\testdup/files'),
        ),
        migrations.AlterField(
            model_name='file',
            name='processed',
            field=models.BooleanField(),
        ),
    ]
