# Generated by Django 4.2.6 on 2023-10-29 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0003_alter_file_file_alter_file_processed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='processed',
            field=models.BooleanField(default=False),
        ),
    ]
